library(venneuler)

png("conditional_vs_intersection.png",width = 1400, height = 700)
venn <- venneuler(c(B = 5000,A = 5000,"A&B" = 1000))
par(mfrow = c(1,2), mar = c(0,3,3,0.5 ))
venn$colors <- c(0.3,0.7)
plot(venn)
par(xpd = TRUE)
rect(-0.1,0,1.05,1,border = "black",lwd = 3)
text(0.5,0.5,expression(A*intersect(B)))
text(0,1.025,  expression(Omega),cex = 2)
title(main = expression(paste(A*intersect(B)," = ",frac(A*intersect(B),1))))
mtext(side = 1,line = -1, text = expression(paste("Area we are considering is ", Omega)),cex = 2)

plot(venn)
text(0.5,0.5,expression(A*intersect(B)))
plotrix::draw.circle(venn$centers[1,1],venn$centers[1,2],venn$diameters[1]/2, lwd = 3)
title(main = expression(paste("A|B = ",frac(A*intersect(B),B))))
text(0.5,0.9, "We have extra information; we know B has happened.", cex = 2)
mtext(side = 1,line = -1, text = "Area we are considering is B ",cex = 2)
dev.off()
